---
- hosts: router
  gather_facts: false
  roles:
    - community.openwrt.init
  tasks:
    - name: Gather OpenWrt facts
      community.openwrt.setup:

    - name: Set hostname
      community.openwrt.uci:
        command: set
        key: system.@system[0].hostname
        value: router

    - name: Disable ipv6
      community.openwrt.uci:
        command: set
        key: network.@device[0].ipv6
        value: '0'

    - name: Setup lan settings
      community.openwrt.uci:
        command: set
        config: network
        section: lan
        value:
          device: br-lan
          proto: static
          ipaddr: 192.168.1.1
          netmask: 255.255.0.0
          delegate: '0'

    - name: Setup wan settings
      community.openwrt.uci:
        command: set
        config: network
        section: wan
        value:
          device: eth1
          proto: dhcp
          peerdns: '0'
          dns: [1.1.1.1, 1.0.0.1, 8.8.8.8, 8.8.4.4]
